name: Run tests
on:
  pull_request:
    branches:
      - staging
      - main
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        cache: 'pip'
        cache-dependency-path: 'requirements.txt'
    - name: Upgrade pip, wheel, setuptools
      run: python -m pip install --upgrade pip wheel setuptools
    - name: Install package
      run: python -m pip install -e .
    - name: Run mypy boto3
      run: python -m mypy_boto3 > /dev/null 2>&1
    - name: Test API
      run: cd api && ./run_tests.sh
  